"Tough Hunk of Bread" = 29.44 --Tough Hunk of Bread
"Freshly Baked Bread" = 288 -- Freshly Baked Bread
"Moist Cornbread" = 244.1 -- Moist Cornbread
"Slitherskin Mackerel" = 0 -- Slitherskin Mackerel
"Longjaw Mud Snapper" = 0 -- Longjaw Mud Snapper
"Bristle Whisker Catfish" = 0 -- Bristle Whisker Catfish
"Forest Mushroom Cap" = 0 -- Forest Mushroom Cap
"Red-speckled Mushroom" = 0 -- Red-speckled Mushroom
"Spongy Morel" = 1 -- Spongy Morel
"Tough Jerky" = 1 -- Tough Jerky
"Haunch of Meat" = 0 -- Haunch of Meat
"Mutton Chop" = 0 -- Mutton Chop
"Darnassian Bleu" = 0 -- Darnassian Bleu
"Dalaran Sharp" = 0 -- Dalaran Sharp
"Dwarven Mild" = 0 -- Dwarven Mild
"Shiny Red Apple" = 6.1 -- Shiny Red Apple
"Tel'Abim Banana" = 10.4 -- Tel-Abim Banana
"Snapvine Watermelon" = 3.6 -- Snapvine Watermelon