WowDiabetesLocalization = {}
WowDiabetesLocalization["DRINK_AURA_NAME"] = "Drink"
WowDiabetesLocalization["FOOD_AURA_NAME"] = "Food"

TITLE_TEXT = "WoW Diabetes"
GLUCOSE_STRING_TEXT = "Glucose"
GLUCOSE_BUTTON_TEXT = "Check"
MEDICINE_STRING_TEXT = "Medicine"
MEDICINE_BUTTON_TEXT = "Use"
CLOSE_BUTTON_TEXT = "Close"
WEBSITE_BUTTON_TEXT = "Website"
UPLOAD_BUTTON_TEXT = "Export"
DOWNLOAD_BUTTON_TEXT = "Import"
GOOD_TEXT = "You are starting to feel better"
OKAY_TEXT = "You are starting to feel dizzy"
BAD_TEXT = "You feel as if you're about to pass out"